spring.application.name=Pacana

spring.security.oauth2.client.registration.github.client-id= Ov23liKFVqFxa4YM4MvC
spring.security.oauth2.client.registration.github.client-secret= 7f80f24c4bffccc776ee42def7b9c8251e9f013d
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.google.client-id=526298588241-fujkubd9sovkk31e6c6siv2ivk1hjmfr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/contacts

logging.level.org.springframework.security=TRACE